# Generated by Django 4.1 on 2022-08-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='nickname',
            field=models.CharField(default='amongus', max_length=255),
            preserve_default=False,
        ),
    ]
